class HumanError(Exception):
    def __init__(self):
        pass